FROM registry.opensource.zalan.do/stups/ubuntu:18.04.1-17
MAINTAINER Zalando SE

# mkdir required because of https://github.com/resin-io-library/base-images/issues/273
RUN mkdir /usr/share/man/man1 && apt-get update && apt-get install --no-install-recommends -y openjdk-11-jdk

# Note: Zalando CA should have been automatically imported into Java trust store by Debian

# Workaround: import all certs manually
RUN for i in /etc/ssl/certs/*.pem; do yes | keytool -importcert -alias $i -keystore /usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts -storepass changeit -file $i; done
RUN keytool -list -keystore /usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts -storepass changeit | grep zalando

ADD utils /java-utils
ENV PATH ${PATH}:/${JAVA_HOME}/bin:/java-utils

CMD ["java", "-version"]

RUN purge.sh
