#!/bin/sh

# Taupage compatible helper script for adding AppDynamics to your JVM process

# example usage:
# exec java $(appdynamics-agent) -jar myfatjar.jar

AGENT_JAR=/agents/appdynamics-jvm/javaagent.jar
[ ! -z "$1" ] && AGENT_JAR=$1

AGENT_OPTS=
[ -f "$AGENT_JAR" ] && AGENT_OPTS=-javaagent:$AGENT_JAR

echo $AGENT_OPTS
